# 30.times do
#
#   Game.create(title: Faker::Game.unique.title, genre: Faker::Game.genre, price: 60)
#   Player.create(username: Faker::Internet.username, wallet: Faker::Number.number(3))
#   Purchase.create(player_id: Player.all.sample.id, game_id: Game.all.sample.id)
#
# end

Game.create(title: "Super Mario World", genre: "", price: 60)
Game.create(title: "The Legend of Zelda: Ocarina of Time", genre: "", price: 60)
Game.create(title: "Portal", genre: "", price: 60)
Game.create(title: "Super Metroid", genre: "", price: 60)
Game.create(title: "Tetris", genre: "", price: 60)
Game.create(title: "Half-Life 2", genre: "", price: 60)
Game.create(title: "Red Dead Redemption", genre: "", price: 60)
Game.create(title: "Castlevania: Symphony of the Night", genre: "", price: 60)
Game.create(title: "Halo: Combat Evolved", genre: "", price: 60)
Game.create(title: "Super Mario Bros.", genre: "", price: 60)
Game.create(title: "Street Fighter II", genre: "", price: 60)
Game.create(title: "Dark Souls", genre: "", price: 60)
Game.create(title: "Grand Theft Auto V", genre: "", price: 60)
Game.create(title: "Chrono Trigger", genre: "", price: 60)
Game.create(title: "Doom", genre: "", price: 60)
Game.create(title: "The Last of Us", genre: "", price: 60)
Game.create(title: "Metal Gear Solid 3: Snake Eater", genre: "", price: 60)
Game.create(title: "Minecraft", genre: "", price: 60)
Game.create(title: "Sid Meier's Civilization IV", genre: "", price: 60)
Game.create(title: "BioShock", genre: "", price: 60)
Game.create(title: "Shadow of the Colossus", genre: "", price: 60)
Game.create(title: "The Witcher 3: Wild Hunt", genre: "", price: 60)
Game.create(title: "Resident Evil 4", genre: "", price: 60)
Game.create(title: "Metroid Prime", genre: "", price: 60)
Game.create(title: "Bloodborne", genre: "", price: 60)
Game.create(title: "Pokemon Yellow", genre: "", price: 60)
Game.create(title: "Mass Effect 2", genre: "", price: 60)
Game.create(title: "Final Fantasy VI", genre: "", price: 60)
Game.create(title: "Star Wars: Knights of the Old Republic", genre: "", price: 60)
Game.create(title: "StarCraft", genre: "", price: 60)
Game.create(title: "Diablo II", genre: "", price: 60)
Game.create(title: "Earthbound", genre: "", price: 60)
Game.create(title: "Persona 4: Golden", genre: "", price: 60)
Game.create(title: "Counter-Strike 1.6", genre: "", price: 60)
Game.create(title: "Ms. Pac-Man", genre: "", price: 60)
Game.create(title: "Baldur's Gate II: Shadows of Amn", genre: "", price: 60)
Game.create(title: "Deus Ex", genre: "", price: 60)
Game.create(title: "Overwatch", genre: "", price: 60)
Game.create(title: "The Legend of Zelda: Majora's Mask", genre: "", price: 60)
Game.create(title: "Uncharted 2: Among Thieves", genre: "", price: 60)
Game.create(title: "Journey", genre: "", price: 60)
Game.create(title: "The Witness", genre: "", price: 60)
Game.create(title: "Batman: Arkham City", genre: "", price: 60)
Game.create(title: "Call Of Duty 4: Modern Warfare", genre: "", price: 60)
Game.create(title: "Silent Hill 2", genre: "", price: 60)
Game.create(title: "Banjo-Kazooie", genre: "", price: 60)
Game.create(title: "Fallout 3", genre: "", price: 60)
Game.create(title: "The Sims", genre: "", price: 60)
Game.create(title: "Team Fortress 2", genre: "", price: 60)
Game.create(title: "Donkey Kong", genre: "", price: 60)
Game.create(title: "Spelunky", genre: "", price: 60)
Game.create(title: "Thief II: The Metal Age", genre: "", price: 60)
Game.create(title: "Dota 2", genre: "", price: 60)
Game.create(title: "Battlefield 1942", genre: "", price: 60)
Game.create(title: "Suikoden II", genre: "", price: 60)
Game.create(title: "X-COM: UFO Defense", genre: "", price: 60)
Game.create(title: "The Elder Scrolls V: Skyrim", genre: "", price: 60)
Game.create(title: "Super Smash Bros. Melee", genre: "", price: 60)
Game.create(title: "GoldenEye 007", genre: "", price: 60)
Game.create(title: "Grim Fandango", genre: "", price: 60)
Game.create(title: "System Shock 2", genre: "", price: 60)
Game.create(title: "Inside", genre: "", price: 60)
Game.create(title: "Contra", genre: "", price: 60)
Game.create(title: "Soulcalibur", genre: "", price: 60)
Game.create(title: "Mega Man 3", genre: "", price: 60)
Game.create(title: "League of Legends", genre: "", price: 60)
Game.create(title: "Undertale", genre: "", price: 60)
Game.create(title: "Burnout 3: Takedown", genre: "", price: 60)
Game.create(title: "Monkey Island 2: LeChuck's Revenge", genre: "", price: 60)
Game.create(title: "The Oregon Trail", genre: "", price: 60)
Game.create(title: "Galaga", genre: "", price: 60)
